/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package winecontrol.telas;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import winecontrol.controladores.ControladorPedidos;
import winecontrol.entidades.ItemDoPedido;
import winecontrol.entidades.Vinho;

/**
 *
 * @author Pedro
 */
public class TelaCarrinho extends javax.swing.JFrame {
    private ControladorPedidos owner;
    private ItemDoPedido carrinho;
    private DefaultTableModel model;
    
    public TelaCarrinho(ControladorPedidos owner) {
        this.owner = owner;
        this.carrinho = owner.carregaCarrinho();
        int linhas=0;
     
        this.model = new DefaultTableModel();
        model.addColumn("Nome");
        model.addColumn("Tipo");
        model.addColumn("Peso");
        model.addColumn("Valor");
        model.addColumn("Descrição");

         for(Vinho vinho : carrinho.getVinhos()){
             if(vinho.getNome()!=null){
                 linhas++;
             }
         }
         this.model.setNumRows(linhas);
          this.listarVinhos();
           initComponents();
            
    }
        public void listarVinhos(){    
            int linha = 0;
            for(Vinho vinho : owner.getVinhos()){
                model.setValueAt(vinho.getNome(),linha,0);
                model.setValueAt(vinho.getTipo(), linha, 1);
                model.setValueAt(vinho.getPeso(), linha, 2);     
                model.setValueAt(vinho.getValor(), linha, 3);
                model.setValueAt(vinho.getDescrição(), linha, 4);
                linha++;
            }
        }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        botaoContinuarComprando = new javax.swing.JButton();
        botaoRemoverVinho = new javax.swing.JButton();
        botaoFinalizarCompra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Seu Carrinho");

        botaoContinuarComprando.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoContinuarComprando.setText("Continuar Comprando");
        botaoContinuarComprando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoContinuarComprandoActionPerformed(evt);
            }
        });

        botaoRemoverVinho.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoRemoverVinho.setText("Remover do Carrinho");
        botaoRemoverVinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverVinhoActionPerformed(evt);
            }
        });

        botaoFinalizarCompra.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoFinalizarCompra.setText("Finalizar Compra");
        botaoFinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFinalizarCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(293, 293, 293))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(botaoContinuarComprando)
                .addGap(49, 49, 49)
                .addComponent(botaoRemoverVinho)
                .addGap(46, 46, 46)
                .addComponent(botaoFinalizarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoContinuarComprando)
                    .addComponent(botaoRemoverVinho)
                    .addComponent(botaoFinalizarCompra))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private String getVinhoSelecionado(){
        String nome = (String) jTable1.getValueAt(jTable1.getSelectedRow(),0);
        
        return nome;
    }
    private void botaoContinuarComprandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoContinuarComprandoActionPerformed
        owner.guardaCarrinho(carrinho);
        owner.exibeTelaCatalogoVinhos();
        setVisible(false);
    }//GEN-LAST:event_botaoContinuarComprandoActionPerformed

    private void botaoRemoverVinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverVinhoActionPerformed
        if(jTable1.getSelectedRowCount()==1){
            Vinho vinho = owner.buscaVinhoNoCarrinho(getVinhoSelecionado(), carrinho);
            carrinho.getVinhos().remove(vinho);   
            owner.guardaCarrinho(carrinho);
            owner.atualizaListaTelaCarrinho();
        }
        else{
            JOptionPane.showMessageDialog(null,"Selecione um vinho para remover!");
        }
    }//GEN-LAST:event_botaoRemoverVinhoActionPerformed

    private void botaoFinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFinalizarCompraActionPerformed
        owner.guardaCarrinho(carrinho);
        this.owner.exibeTelaPedido();
        setVisible(false);
        
    }//GEN-LAST:event_botaoFinalizarCompraActionPerformed

   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoContinuarComprando;
    private javax.swing.JButton botaoFinalizarCompra;
    private javax.swing.JButton botaoRemoverVinho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

   

}
